name: consulti.mx
favicon: null
layout_spectrum: 0.49615
typography_spectrum: 0.65325
title: Estrategia y Consultor√≠a en TI
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#ff2a1d'
    - '#1982a4'
    - '#45555a'
    - '#ff7a71'
  brandStrength: 0.4784129175823182
  lightness: 0.25
  saturation: 0.6294027536641806
  rhythmicContrast: 1
purpose: []
